# -*- coding: utf-8 -*-
# Ghidra post-analysis dump for canon-tool R3 (TIN-1695).
# Runs under analyzeHeadless as a postScript (Jython 2.7).
#
# Extracts the static-analysis anchors the TIN-1697 trace starts from:
#   - recovered C++ classes (RTTI), esp. CEEPROM* MFC dialog/handler classes
#   - imported functions (USB / file I/O primitives the maintenance write uses)
#   - defined strings matching maintenance/model keywords
#   - program metadata (image base, compiler, function count)
#
# Output: a markdown report written to the path passed as the first script arg.

import codecs

from ghidra.program.util import DefinedDataIterator
from ghidra.program.model.symbol import SymbolType

args = getScriptArgs()
OUT = args[0] if args and len(args) > 0 else "/tmp/canon-ghidra-report.md"

prog = currentProgram
fm = prog.getFunctionManager()
st = prog.getSymbolTable()

lines = []
def w(s=u""):
    # Coerce everything to unicode so join/write never hits the ascii codec
    # (markdown literals contain em-dashes; binary strings can be any encoding).
    if not isinstance(s, unicode):
        s = unicode(str(s), "utf-8", "replace")
    lines.append(s)

# ---- keyword sets ---------------------------------------------------------
# Maintenance / EEPROM / counter vocabulary + model strings of interest.
KW_SYM = ["eeprom", "absorber", "waste", "ink", "counter", "reset",
          "maintenance", "service", "dump", "usb", "writefile",
          "deviceiocontrol", "bulk", "ieee1284", "centronics"]
KW_STR = ["g3010", "g6020", "g3000", "g7020", "g4010", "absorber", "waste",
          "ink", "counter", "eeprom", "reset", "maintenance", "service tool",
          "5b00", "support code", "\\\\.\\", "usbprint", "winusb"]
KW_IMPORT = ["writefile", "readfile", "deviceiocontrol", "createfile",
             "winusb", "setupdi", "closehandle", "hidd", "hid_"]

def matches(name, kws):
    n = name.lower()
    return [k for k in kws if k in n]

# ---- program metadata -----------------------------------------------------
w("# canon-tool R3 — Ghidra static-analysis dump (v5103)")
w()
w("_Generated by `.ghidra-work/scripts/dump_canon.py` via analyzeHeadless._")
w()
w("## Program metadata")
w()
w("| field | value |")
w("|---|---|")
w("| name | `%s` |" % prog.getName())
w("| format | %s |" % prog.getExecutableFormat())
w("| language | %s |" % prog.getLanguageID())
w("| compiler | %s |" % prog.getCompilerSpec().getCompilerSpecID())
w("| image base | %s |" % prog.getImageBase())
w("| function count | %d |" % fm.getFunctionCount())
w("| symbol count | %d |" % st.getNumSymbols())
w()

# ---- recovered C++ classes (RTTI) -----------------------------------------
w("## Recovered C++ classes (RTTI namespaces)")
w()
classes = []
try:
    it = st.getClassNamespaces()
    while it.hasNext():
        classes.append(it.next())
except Exception as e:
    w("_getClassNamespaces failed: %s_" % e)

ceeprom = [c for c in classes if "eeprom" in c.getName().lower()]
w("Total recovered classes: **%d**" % len(classes))
w()
w("### CEEPROM* / EEPROM-related classes (the absorber-reset anchors)")
w()
if ceeprom:
    w("| class | symbol address |")
    w("|---|---|")
    for c in sorted(ceeprom, key=lambda x: x.getName()):
        sym = c.getSymbol()
        addr = sym.getAddress() if sym is not None else "?"
        w("| `%s` | %s |" % (c.getName(True), addr))
else:
    w("_None matched 'eeprom' in class name — RTTI may not have recovered them; "
      "check symbol scan below._")
w()

# A broader class list (names only) helps the trace ticket orient.
w("### All recovered class names (first 120)")
w()
names = sorted(set(c.getName() for c in classes))
w("```")
for n in names[:120]:
    w(n)
if len(names) > 120:
    w("... (%d more names omitted)" % (len(names) - 120))
w("```")
w()

# ---- symbols matching maintenance vocabulary ------------------------------
w("## Symbols matching maintenance/USB vocabulary")
w()
sym_hits = {}
for sym in st.getAllSymbols(True):
    nm = sym.getName()
    hit = matches(nm, KW_SYM)
    if hit:
        key = nm
        if key not in sym_hits:
            sym_hits[key] = (sym.getAddress(), sym.getSymbolType(), set(hit))
        else:
            sym_hits[key][2].update(hit)

w("Matched **%d** distinct symbol names. Showing up to 200, sorted:" % len(sym_hits))
w()
w("| symbol | address | type | kw |")
w("|---|---|---|---|")
for nm in sorted(sym_hits.keys())[:200]:
    addr, stype, hits = sym_hits[nm]
    safe = nm.replace("|", "\\|")
    w("| `%s` | %s | %s | %s |" % (safe, addr, stype, ",".join(sorted(hits))))
w()

# ---- imported functions (USB / file I/O primitives) -----------------------
w("## Imported functions (external) — USB / I/O primitives")
w()
imports = []
try:
    for f in fm.getExternalFunctions():
        lib = f.getExternalLocation().getLibraryName() if f.getExternalLocation() else "?"
        imports.append((f.getName(), lib))
except Exception as e:
    w("_getExternalFunctions failed: %s_" % e)

io_imports = [(n, l) for (n, l) in imports if matches(n, KW_IMPORT)]
w("Total external functions: **%d**; I/O-primitive matches: **%d**" %
  (len(imports), len(io_imports)))
w()
w("### I/O / USB primitive imports (the write call-site candidates)")
w()
if io_imports:
    w("| function | library |")
    w("|---|---|")
    for n, l in sorted(set(io_imports)):
        w("| `%s` | %s |" % (n, l))
else:
    w("_No direct WriteFile/DeviceIoControl/WinUSB imports — the USB write may go "
      "through a helper DLL (check the full import list below) or LoadLibrary._")
w()
w("### All imported libraries + function counts")
w()
libcount = {}
for n, l in imports:
    libcount[l] = libcount.get(l, 0) + 1
w("| library | import count |")
w("|---|---|")
for l in sorted(libcount.keys()):
    w("| %s | %d |" % (l, libcount[l]))
w()

# ---- defined strings matching keywords ------------------------------------
w("## Defined strings matching model/maintenance keywords")
w()
str_hits = []
try:
    for d in DefinedDataIterator.definedStrings(prog):
        try:
            val = d.getValue()
        except Exception:
            continue
        if val is None:
            continue
        sval = unicode(val)
        hit = matches(sval, KW_STR)
        if hit:
            str_hits.append((d.getAddress(), sval, hit))
except Exception as e:
    w("_definedStrings failed: %s_" % e)

w("Matched **%d** strings. Showing up to 250:" % len(str_hits))
w()
w("| address | kw | string |")
w("|---|---|---|")
for addr, sval, hit in str_hits[:250]:
    safe = sval.replace("|", "\\|").replace("\n", "\\n").replace("\r", "\\r")
    if len(safe) > 120:
        safe = safe[:120] + "..."
    w("| %s | %s | `%s` |" % (addr, ",".join(sorted(set(hit))), safe))
w()

# ---- write report ---------------------------------------------------------
f = codecs.open(OUT, "w", "utf-8")
f.write(u"\n".join(lines))
f.write(u"\n")
f.close()

println("CANON_DUMP_WROTE " + OUT)
println("CANON_DUMP_CLASSES %d  CEEPROM %d  SYMHITS %d  IMPORTS %d  IOIMPORTS %d  STRHITS %d" %
        (len(classes), len(ceeprom), len(sym_hits), len(imports), len(io_imports), len(str_hits)))
