#!/usr/bin/env python3
"""safe-ping-probe — read documented-safe baseline data from a connected Canon
G-series printer over USB.

These probes are ALL spec-defined safe ops:
- IEEE-1284 GET_DEVICE_ID (USB printer class standard request 0x00)
- USB device descriptors (read-only)
- USB configuration + interface descriptors (read-only)

No bulk-OUT writes. No vendor-specific commands. No EEPROM access. This is
the absolute floor of safe interaction and characterizes the locked
baseline ping suite.

The output is YAML-formatted, ready for `printers/canon-g6020/maintenance.yaml`
under `ping_suite_baseline:`.

Usage:
    sudo python3 safe-ping-probe.py [--vendor 04a9] [--product 1865]

Run as root or as a member of the `printstack` group (per the udev rule
installed by the `canon_tool_dev` ansible role).
"""

from __future__ import annotations

import argparse
import datetime
import sys
from typing import Any

import usb.core
import usb.util


def hex_dump(data: bytes, sep: str = ":") -> str:
    return sep.join(f"{b:02x}" for b in data)


def find_device(vendor: int, product: int) -> usb.core.Device:
    dev = usb.core.find(idVendor=vendor, idProduct=product)
    if dev is None:
        sys.stderr.write(
            f"# error: no USB device matching {vendor:#06x}:{product:#06x} on bus\n"
        )
        sys.exit(2)
    return dev


def yaml_block_safe(s: str, indent: int = 4) -> str:
    """Render a string as a single-line YAML block, escaping where needed."""
    if "'" in s or "\n" in s:
        return repr(s)
    return f"'{s}'"


def describe_endpoints(intf: usb.core.Interface) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for ep in intf:
        ep_type_id = usb.util.endpoint_type(ep.bmAttributes)
        ep_type_name = {
            usb.util.ENDPOINT_TYPE_BULK: "BULK",
            usb.util.ENDPOINT_TYPE_INTR: "INTERRUPT",
            usb.util.ENDPOINT_TYPE_ISO: "ISOCHRONOUS",
            usb.util.ENDPOINT_TYPE_CTRL: "CONTROL",
        }.get(ep_type_id, "?")
        ep_dir_id = usb.util.endpoint_direction(ep.bEndpointAddress)
        ep_dir = "IN" if ep_dir_id == usb.util.ENDPOINT_IN else "OUT"
        out.append(
            {
                "address": ep.bEndpointAddress,
                "direction": ep_dir,
                "type": ep_type_name,
                "max_packet_size": ep.wMaxPacketSize,
                "interval": ep.bInterval,
            }
        )
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--vendor", default="04a9", help="USB vendor id (hex)")
    parser.add_argument("--product", default="1865", help="USB product id (hex)")
    args = parser.parse_args()

    vendor = int(args.vendor, 16)
    product = int(args.product, 16)

    dev = find_device(vendor, product)
    ts = datetime.datetime.now(datetime.UTC).isoformat()

    print("# Generated by services/canon-tool/scripts/safe-ping-probe.py")
    print(f"# Captured: {ts}")
    print()
    print("ping_suite_baseline:")
    print(f"  captured_at: '{ts}'")
    print("  usb_descriptors:")
    print(f"    vendor_id: '0x{dev.idVendor:04x}'")
    print(f"    product_id: '0x{dev.idProduct:04x}'")
    print(f"    bcd_device: '0x{dev.bcdDevice:04x}'")
    print(f"    device_class: '0x{dev.bDeviceClass:02x}'")
    print(f"    device_sub_class: '0x{dev.bDeviceSubClass:02x}'")
    print(f"    device_protocol: '0x{dev.bDeviceProtocol:02x}'")

    # Try to read the iManufacturer / iProduct / iSerialNumber strings.
    for label, idx_attr in (
        ("manufacturer_string", "iManufacturer"),
        ("product_string", "iProduct"),
        ("serial_number_string", "iSerialNumber"),
    ):
        try:
            idx = getattr(dev, idx_attr)
            if idx == 0:
                print(f"    {label}: null  # iIndex was 0")
            else:
                val = usb.util.get_string(dev, idx)
                print(f"    {label}: {yaml_block_safe(val or '')}")
        except (usb.core.USBError, ValueError) as exc:
            print(f"    {label}: null  # read error: {exc}")

    # Detach kernel driver (ipp-usb is normally bound) so we can claim
    # interface 0 for the IEEE-1284 GET_DEVICE_ID control transfer.
    kernel_was_attached = False
    try:
        if dev.is_kernel_driver_active(0):
            kernel_was_attached = True
            dev.detach_kernel_driver(0)
    except (NotImplementedError, usb.core.USBError):
        pass

    try:
        try:
            dev.set_configuration()
        except usb.core.USBError as exc:
            # Resource busy = ipp-usb's user-space libusb handle is open.
            # The device is already configured from its perspective; we can
            # often still get_active_configuration() and proceed.
            if exc.errno == 16:
                print(f"  # note: set_configuration() returned EBUSY (ipp-usb holds the device); proceeding read-only")
            else:
                raise
        cfg = dev.get_active_configuration()

        print(f"  active_configuration:")
        print(f"    num_interfaces: {cfg.bNumInterfaces}")
        print(f"    self_powered: {(cfg.bmAttributes & 0x40) >> 6}")
        print(f"    max_power_mA: {cfg.bMaxPower * 2}")
        print(f"    interfaces:")

        for intf in cfg:
            print(f"      - number: {intf.bInterfaceNumber}")
            print(f"        alt_setting: {intf.bAlternateSetting}")
            print(f"        class: '0x{intf.bInterfaceClass:02x}'")
            print(f"        sub_class: '0x{intf.bInterfaceSubClass:02x}'")
            print(f"        protocol: '0x{intf.bInterfaceProtocol:02x}'")
            eps = describe_endpoints(intf)
            print(f"        endpoints:")
            for ep in eps:
                print(f"          - address: '0x{ep['address']:02x}'")
                print(f"            direction: '{ep['direction']}'")
                print(f"            type: '{ep['type']}'")
                print(f"            max_packet_size: {ep['max_packet_size']}")
                print(f"            interval: {ep['interval']}")

        # IEEE 1284 GET_DEVICE_ID — spec-defined safe control transfer.
        # bmRequestType: 10100001b (class, interface, device-to-host)
        # bRequest: 0x00 (GET_DEVICE_ID)
        # wValue: configuration index (typically 0)
        # wIndex: high byte = interface, low byte = alt setting
        print(f"  ieee_1284_device_id:")
        try:
            for intf in cfg:
                if intf.bInterfaceClass == 0x07:  # USB-IF printer class
                    response = dev.ctrl_transfer(
                        bmRequestType=0xA1,
                        bRequest=0x00,
                        wValue=0,
                        wIndex=intf.bInterfaceNumber << 8,
                        data_or_wLength=1024,
                        timeout=3000,
                    )
                    raw = bytes(response)
                    if len(raw) >= 2:
                        length = (raw[0] << 8) | raw[1]
                        payload = raw[2 : 2 + length].decode("ascii", errors="replace")
                        print(f"    interface: {intf.bInterfaceNumber}")
                        print(f"    raw_length_bytes: {len(raw)}")
                        print(f"    declared_length: {length}")
                        print(f"    payload: {yaml_block_safe(payload)}")
                        # Parsed CMD set
                        for part in payload.split(";"):
                            if part.startswith("CMD:"):
                                cmds = part[4:].split(",")
                                print(f"    parsed_cmd_set:")
                                for c in cmds:
                                    print(f"      - {yaml_block_safe(c)}")
                                break
                        # Try other printer-class interfaces too.
                    break
            else:
                print("    note: 'no USB-IF printer class interface (0x07) found'")
        except usb.core.USBError as exc:
            print(f"    error: '{exc}'")

    finally:
        try:
            usb.util.dispose_resources(dev)
            if kernel_was_attached:
                try:
                    dev.attach_kernel_driver(0)
                except (NotImplementedError, usb.core.USBError):
                    pass
        except Exception:
            pass

    return 0


if __name__ == "__main__":
    sys.exit(main())
